// Package syncclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package syncclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ManifestFlagType.
const (
	ManifestFlagTypeBoolean ManifestFlagType = "boolean"
	ManifestFlagTypeNumber  ManifestFlagType = "number"
	ManifestFlagTypeObject  ManifestFlagType = "object"
	ManifestFlagTypeString  ManifestFlagType = "string"
)

// Valid indicates whether the value is a known member of the ManifestFlagType enum.
func (e ManifestFlagType) Valid() bool {
	switch e {
	case ManifestFlagTypeBoolean:
		return true
	case ManifestFlagTypeNumber:
		return true
	case ManifestFlagTypeObject:
		return true
	case ManifestFlagTypeString:
		return true
	default:
		return false
	}
}

// Defines values for PostOpenfeatureV0ManifestFlagsJSONBodyType.
const (
	PostOpenfeatureV0ManifestFlagsJSONBodyTypeBoolean PostOpenfeatureV0ManifestFlagsJSONBodyType = "boolean"
	PostOpenfeatureV0ManifestFlagsJSONBodyTypeNumber  PostOpenfeatureV0ManifestFlagsJSONBodyType = "number"
	PostOpenfeatureV0ManifestFlagsJSONBodyTypeObject  PostOpenfeatureV0ManifestFlagsJSONBodyType = "object"
	PostOpenfeatureV0ManifestFlagsJSONBodyTypeString  PostOpenfeatureV0ManifestFlagsJSONBodyType = "string"
)

// Valid indicates whether the value is a known member of the PostOpenfeatureV0ManifestFlagsJSONBodyType enum.
func (e PostOpenfeatureV0ManifestFlagsJSONBodyType) Valid() bool {
	switch e {
	case PostOpenfeatureV0ManifestFlagsJSONBodyTypeBoolean:
		return true
	case PostOpenfeatureV0ManifestFlagsJSONBodyTypeNumber:
		return true
	case PostOpenfeatureV0ManifestFlagsJSONBodyTypeObject:
		return true
	case PostOpenfeatureV0ManifestFlagsJSONBodyTypeString:
		return true
	default:
		return false
	}
}

// Defines values for PutOpenfeatureV0ManifestFlagsKeyJSONBodyType.
const (
	Boolean PutOpenfeatureV0ManifestFlagsKeyJSONBodyType = "boolean"
	Number  PutOpenfeatureV0ManifestFlagsKeyJSONBodyType = "number"
	Object  PutOpenfeatureV0ManifestFlagsKeyJSONBodyType = "object"
	String  PutOpenfeatureV0ManifestFlagsKeyJSONBodyType = "string"
)

// Valid indicates whether the value is a known member of the PutOpenfeatureV0ManifestFlagsKeyJSONBodyType enum.
func (e PutOpenfeatureV0ManifestFlagsKeyJSONBodyType) Valid() bool {
	switch e {
	case Boolean:
		return true
	case Number:
		return true
	case Object:
		return true
	case String:
		return true
	default:
		return false
	}
}

// ArchiveResponse defines model for ArchiveResponse.
type ArchiveResponse struct {
	// ArchivedAt Timestamp recording when the flag was archived.
	ArchivedAt *time.Time `json:"archivedAt"`
	Message    string     `json:"message"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Code Short machine-readable code (matches Zod issue codes).
	Code *string `json:"code,omitempty"`

	// Field Field path related to the error.
	Field *string `json:"field,omitempty"`

	// Message Human-friendly error message.
	Message *string `json:"message,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Details *[]ErrorDetail `json:"details,omitempty"`
		Message string         `json:"message"`
		Status  int            `json:"status"`
	} `json:"error"`
}

// FlagDefaultValue Default value for a flag (can be boolean, string, number, or object)
type FlagDefaultValue struct {
	union json.RawMessage
}

// FlagDefaultValue0 defines model for .
type FlagDefaultValue0 = bool

// FlagDefaultValue1 defines model for .
type FlagDefaultValue1 = string

// FlagDefaultValue2 defines model for .
type FlagDefaultValue2 = float32

// FlagDefaultValue3 defines model for .
type FlagDefaultValue3 = map[string]interface{}

// ManifestEnvelope defines model for ManifestEnvelope.
type ManifestEnvelope struct {
	Flags []ManifestFlag `json:"flags"`
}

// ManifestFlag defines model for ManifestFlag.
type ManifestFlag struct {
	// DefaultValue Default value for a flag (can be boolean, string, number, or object)
	DefaultValue FlagDefaultValue `json:"defaultValue"`

	// Description Optional flag description.
	Description *string `json:"description,omitempty"`

	// Key Unique flag key within the flag set.
	Key string `json:"key"`

	// Name Human-friendly flag name. Defaults to the key when omitted.
	Name *string `json:"name,omitempty"`

	// Type Flag data type.
	Type ManifestFlagType `json:"type"`
}

// ManifestFlagType Flag data type.
type ManifestFlagType string

// ManifestFlagResponse defines model for ManifestFlagResponse.
type ManifestFlagResponse struct {
	Flag ManifestFlag `json:"flag"`

	// UpdatedAt ISO timestamp reflecting the last update to the flag record. Clients can use this to
	// detect changes between manifest fetches or to implement optimistic concurrency checks.
	UpdatedAt time.Time `json:"updatedAt"`
}

// PostOpenfeatureV0ManifestFlagsJSONBody defines parameters for PostOpenfeatureV0ManifestFlags.
type PostOpenfeatureV0ManifestFlagsJSONBody struct {
	// DefaultValue Default value for a flag (can be boolean, string, number, or object)
	DefaultValue FlagDefaultValue `json:"defaultValue"`
	Description  *string          `json:"description,omitempty"`
	Key          string           `json:"key"`

	// Name Optional display name. Defaults to the key.
	Name *string                                    `json:"name,omitempty"`
	Type PostOpenfeatureV0ManifestFlagsJSONBodyType `json:"type"`
}

// PostOpenfeatureV0ManifestFlagsJSONBodyType defines parameters for PostOpenfeatureV0ManifestFlags.
type PostOpenfeatureV0ManifestFlagsJSONBodyType string

// PutOpenfeatureV0ManifestFlagsKeyJSONBody defines parameters for PutOpenfeatureV0ManifestFlagsKey.
type PutOpenfeatureV0ManifestFlagsKeyJSONBody struct {
	// DefaultValue Default value for a flag (can be boolean, string, number, or object)
	DefaultValue *FlagDefaultValue                            `json:"defaultValue,omitempty"`
	Description  *string                                      `json:"description,omitempty"`
	Key          string                                       `json:"key"`
	Name         *string                                      `json:"name,omitempty"`
	Type         PutOpenfeatureV0ManifestFlagsKeyJSONBodyType `json:"type"`
}

// PutOpenfeatureV0ManifestFlagsKeyJSONBodyType defines parameters for PutOpenfeatureV0ManifestFlagsKey.
type PutOpenfeatureV0ManifestFlagsKeyJSONBodyType string

// PostOpenfeatureV0ManifestFlagsJSONRequestBody defines body for PostOpenfeatureV0ManifestFlags for application/json ContentType.
type PostOpenfeatureV0ManifestFlagsJSONRequestBody PostOpenfeatureV0ManifestFlagsJSONBody

// PutOpenfeatureV0ManifestFlagsKeyJSONRequestBody defines body for PutOpenfeatureV0ManifestFlagsKey for application/json ContentType.
type PutOpenfeatureV0ManifestFlagsKeyJSONRequestBody PutOpenfeatureV0ManifestFlagsKeyJSONBody

// AsFlagDefaultValue0 returns the union data inside the FlagDefaultValue as a FlagDefaultValue0
func (t FlagDefaultValue) AsFlagDefaultValue0() (FlagDefaultValue0, error) {
	var body FlagDefaultValue0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFlagDefaultValue0 overwrites any union data inside the FlagDefaultValue as the provided FlagDefaultValue0
func (t *FlagDefaultValue) FromFlagDefaultValue0(v FlagDefaultValue0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFlagDefaultValue0 performs a merge with any union data inside the FlagDefaultValue, using the provided FlagDefaultValue0
func (t *FlagDefaultValue) MergeFlagDefaultValue0(v FlagDefaultValue0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFlagDefaultValue1 returns the union data inside the FlagDefaultValue as a FlagDefaultValue1
func (t FlagDefaultValue) AsFlagDefaultValue1() (FlagDefaultValue1, error) {
	var body FlagDefaultValue1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFlagDefaultValue1 overwrites any union data inside the FlagDefaultValue as the provided FlagDefaultValue1
func (t *FlagDefaultValue) FromFlagDefaultValue1(v FlagDefaultValue1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFlagDefaultValue1 performs a merge with any union data inside the FlagDefaultValue, using the provided FlagDefaultValue1
func (t *FlagDefaultValue) MergeFlagDefaultValue1(v FlagDefaultValue1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFlagDefaultValue2 returns the union data inside the FlagDefaultValue as a FlagDefaultValue2
func (t FlagDefaultValue) AsFlagDefaultValue2() (FlagDefaultValue2, error) {
	var body FlagDefaultValue2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFlagDefaultValue2 overwrites any union data inside the FlagDefaultValue as the provided FlagDefaultValue2
func (t *FlagDefaultValue) FromFlagDefaultValue2(v FlagDefaultValue2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFlagDefaultValue2 performs a merge with any union data inside the FlagDefaultValue, using the provided FlagDefaultValue2
func (t *FlagDefaultValue) MergeFlagDefaultValue2(v FlagDefaultValue2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFlagDefaultValue3 returns the union data inside the FlagDefaultValue as a FlagDefaultValue3
func (t FlagDefaultValue) AsFlagDefaultValue3() (FlagDefaultValue3, error) {
	var body FlagDefaultValue3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFlagDefaultValue3 overwrites any union data inside the FlagDefaultValue as the provided FlagDefaultValue3
func (t *FlagDefaultValue) FromFlagDefaultValue3(v FlagDefaultValue3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFlagDefaultValue3 performs a merge with any union data inside the FlagDefaultValue, using the provided FlagDefaultValue3
func (t *FlagDefaultValue) MergeFlagDefaultValue3(v FlagDefaultValue3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FlagDefaultValue) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *FlagDefaultValue) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetOpenfeatureV0Manifest request
	GetOpenfeatureV0Manifest(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostOpenfeatureV0ManifestFlagsWithBody request with any body
	PostOpenfeatureV0ManifestFlagsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostOpenfeatureV0ManifestFlags(ctx context.Context, body PostOpenfeatureV0ManifestFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteOpenfeatureV0ManifestFlagsKey request
	DeleteOpenfeatureV0ManifestFlagsKey(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutOpenfeatureV0ManifestFlagsKeyWithBody request with any body
	PutOpenfeatureV0ManifestFlagsKeyWithBody(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutOpenfeatureV0ManifestFlagsKey(ctx context.Context, key string, body PutOpenfeatureV0ManifestFlagsKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetOpenfeatureV0Manifest(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOpenfeatureV0ManifestRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOpenfeatureV0ManifestFlagsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOpenfeatureV0ManifestFlagsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOpenfeatureV0ManifestFlags(ctx context.Context, body PostOpenfeatureV0ManifestFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOpenfeatureV0ManifestFlagsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteOpenfeatureV0ManifestFlagsKey(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteOpenfeatureV0ManifestFlagsKeyRequest(c.Server, key)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutOpenfeatureV0ManifestFlagsKeyWithBody(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutOpenfeatureV0ManifestFlagsKeyRequestWithBody(c.Server, key, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutOpenfeatureV0ManifestFlagsKey(ctx context.Context, key string, body PutOpenfeatureV0ManifestFlagsKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutOpenfeatureV0ManifestFlagsKeyRequest(c.Server, key, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetOpenfeatureV0ManifestRequest generates requests for GetOpenfeatureV0Manifest
func NewGetOpenfeatureV0ManifestRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/openfeature/v0/manifest")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostOpenfeatureV0ManifestFlagsRequest calls the generic PostOpenfeatureV0ManifestFlags builder with application/json body
func NewPostOpenfeatureV0ManifestFlagsRequest(server string, body PostOpenfeatureV0ManifestFlagsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostOpenfeatureV0ManifestFlagsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostOpenfeatureV0ManifestFlagsRequestWithBody generates requests for PostOpenfeatureV0ManifestFlags with any type of body
func NewPostOpenfeatureV0ManifestFlagsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/openfeature/v0/manifest/flags")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteOpenfeatureV0ManifestFlagsKeyRequest generates requests for DeleteOpenfeatureV0ManifestFlagsKey
func NewDeleteOpenfeatureV0ManifestFlagsKeyRequest(server string, key string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "key", key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/openfeature/v0/manifest/flags/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutOpenfeatureV0ManifestFlagsKeyRequest calls the generic PutOpenfeatureV0ManifestFlagsKey builder with application/json body
func NewPutOpenfeatureV0ManifestFlagsKeyRequest(server string, key string, body PutOpenfeatureV0ManifestFlagsKeyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutOpenfeatureV0ManifestFlagsKeyRequestWithBody(server, key, "application/json", bodyReader)
}

// NewPutOpenfeatureV0ManifestFlagsKeyRequestWithBody generates requests for PutOpenfeatureV0ManifestFlagsKey with any type of body
func NewPutOpenfeatureV0ManifestFlagsKeyRequestWithBody(server string, key string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "key", key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/openfeature/v0/manifest/flags/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetOpenfeatureV0ManifestWithResponse request
	GetOpenfeatureV0ManifestWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetOpenfeatureV0ManifestResponse, error)

	// PostOpenfeatureV0ManifestFlagsWithBodyWithResponse request with any body
	PostOpenfeatureV0ManifestFlagsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOpenfeatureV0ManifestFlagsResponse, error)

	PostOpenfeatureV0ManifestFlagsWithResponse(ctx context.Context, body PostOpenfeatureV0ManifestFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOpenfeatureV0ManifestFlagsResponse, error)

	// DeleteOpenfeatureV0ManifestFlagsKeyWithResponse request
	DeleteOpenfeatureV0ManifestFlagsKeyWithResponse(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*DeleteOpenfeatureV0ManifestFlagsKeyResponse, error)

	// PutOpenfeatureV0ManifestFlagsKeyWithBodyWithResponse request with any body
	PutOpenfeatureV0ManifestFlagsKeyWithBodyWithResponse(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutOpenfeatureV0ManifestFlagsKeyResponse, error)

	PutOpenfeatureV0ManifestFlagsKeyWithResponse(ctx context.Context, key string, body PutOpenfeatureV0ManifestFlagsKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*PutOpenfeatureV0ManifestFlagsKeyResponse, error)
}

type GetOpenfeatureV0ManifestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ManifestEnvelope
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetOpenfeatureV0ManifestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOpenfeatureV0ManifestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostOpenfeatureV0ManifestFlagsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ManifestFlagResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostOpenfeatureV0ManifestFlagsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostOpenfeatureV0ManifestFlagsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteOpenfeatureV0ManifestFlagsKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ArchiveResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
	JSON409      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteOpenfeatureV0ManifestFlagsKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteOpenfeatureV0ManifestFlagsKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutOpenfeatureV0ManifestFlagsKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ManifestFlagResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PutOpenfeatureV0ManifestFlagsKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutOpenfeatureV0ManifestFlagsKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetOpenfeatureV0ManifestWithResponse request returning *GetOpenfeatureV0ManifestResponse
func (c *ClientWithResponses) GetOpenfeatureV0ManifestWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetOpenfeatureV0ManifestResponse, error) {
	rsp, err := c.GetOpenfeatureV0Manifest(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOpenfeatureV0ManifestResponse(rsp)
}

// PostOpenfeatureV0ManifestFlagsWithBodyWithResponse request with arbitrary body returning *PostOpenfeatureV0ManifestFlagsResponse
func (c *ClientWithResponses) PostOpenfeatureV0ManifestFlagsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOpenfeatureV0ManifestFlagsResponse, error) {
	rsp, err := c.PostOpenfeatureV0ManifestFlagsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOpenfeatureV0ManifestFlagsResponse(rsp)
}

func (c *ClientWithResponses) PostOpenfeatureV0ManifestFlagsWithResponse(ctx context.Context, body PostOpenfeatureV0ManifestFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOpenfeatureV0ManifestFlagsResponse, error) {
	rsp, err := c.PostOpenfeatureV0ManifestFlags(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOpenfeatureV0ManifestFlagsResponse(rsp)
}

// DeleteOpenfeatureV0ManifestFlagsKeyWithResponse request returning *DeleteOpenfeatureV0ManifestFlagsKeyResponse
func (c *ClientWithResponses) DeleteOpenfeatureV0ManifestFlagsKeyWithResponse(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*DeleteOpenfeatureV0ManifestFlagsKeyResponse, error) {
	rsp, err := c.DeleteOpenfeatureV0ManifestFlagsKey(ctx, key, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteOpenfeatureV0ManifestFlagsKeyResponse(rsp)
}

// PutOpenfeatureV0ManifestFlagsKeyWithBodyWithResponse request with arbitrary body returning *PutOpenfeatureV0ManifestFlagsKeyResponse
func (c *ClientWithResponses) PutOpenfeatureV0ManifestFlagsKeyWithBodyWithResponse(ctx context.Context, key string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutOpenfeatureV0ManifestFlagsKeyResponse, error) {
	rsp, err := c.PutOpenfeatureV0ManifestFlagsKeyWithBody(ctx, key, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutOpenfeatureV0ManifestFlagsKeyResponse(rsp)
}

func (c *ClientWithResponses) PutOpenfeatureV0ManifestFlagsKeyWithResponse(ctx context.Context, key string, body PutOpenfeatureV0ManifestFlagsKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*PutOpenfeatureV0ManifestFlagsKeyResponse, error) {
	rsp, err := c.PutOpenfeatureV0ManifestFlagsKey(ctx, key, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutOpenfeatureV0ManifestFlagsKeyResponse(rsp)
}

// ParseGetOpenfeatureV0ManifestResponse parses an HTTP response from a GetOpenfeatureV0ManifestWithResponse call
func ParseGetOpenfeatureV0ManifestResponse(rsp *http.Response) (*GetOpenfeatureV0ManifestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOpenfeatureV0ManifestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ManifestEnvelope
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostOpenfeatureV0ManifestFlagsResponse parses an HTTP response from a PostOpenfeatureV0ManifestFlagsWithResponse call
func ParsePostOpenfeatureV0ManifestFlagsResponse(rsp *http.Response) (*PostOpenfeatureV0ManifestFlagsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostOpenfeatureV0ManifestFlagsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ManifestFlagResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteOpenfeatureV0ManifestFlagsKeyResponse parses an HTTP response from a DeleteOpenfeatureV0ManifestFlagsKeyWithResponse call
func ParseDeleteOpenfeatureV0ManifestFlagsKeyResponse(rsp *http.Response) (*DeleteOpenfeatureV0ManifestFlagsKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteOpenfeatureV0ManifestFlagsKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ArchiveResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParsePutOpenfeatureV0ManifestFlagsKeyResponse parses an HTTP response from a PutOpenfeatureV0ManifestFlagsKeyWithResponse call
func ParsePutOpenfeatureV0ManifestFlagsKeyResponse(rsp *http.Response) (*PutOpenfeatureV0ManifestFlagsKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutOpenfeatureV0ManifestFlagsKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ManifestFlagResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
